import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./Components/LandPage/Header/Header";

const neueSans = localFont({
  src: [
    { path: "./fonts/NeueHaasDisplayMediu.ttf", weight: "500" },
    { path: "./fonts/NeueHaasDisplayRoman.ttf", weight: "400" },
  ],
  variable: "--font-neue",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${neueSans.variable} antialiased`}>{children}</body>
    </html>
  );
}
